name: "Build Binary"

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Create custom vars
        env:
          RUN_NUMBER: ${{ github.run_number }}
        id: custom-vars
        run: |
          echo "BUILD_VERSION=v$(date +%Y.%m).$RUN_NUM" >> $GITHUB_OUTPUT
      - name: Create tag
        # https://stackoverflow.com/questions/60963759/use-github-actions-to-create-a-tag-but-not-a-release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.custom-vars.outputs.BUILD_VERSION }}',
              sha: context.sha
            })
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Prepare Source
        run: |
          go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --auto-snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.custom-vars.outputs.BUILD_VERSION }}
          GORELEASER_CURRENT_TAG: ${{ steps.custom-vars.outputs.BUILD_VERSION }}
